### ISSUE TITLE
TODOs Tamara

### ISSUE THREAD

**Issue by muhkuhxy** [muhkuhxy/ironleaves-photography#172]
- [x] Bei Bildlooks Teaser Text klar machen, dass photoshoppen gemeint ist
- [x] Best of Slider Bilder aussuchen
- [x] Design-Link für Papeterie texten

**Comment by Ironleaves** [comment]
Optional könnt ihr die Bildbearbeitung und die Anmutung Eurer Fotos mitbestimmen.

Eure Fotos sollen Euch und Euren Charakter widerspiegeln und Eure Hochzeit genau so wiedergeben, wie ihr sie in Erinnerung habt. Mögt ihr rustikale, dunkle und warme Bilder? Oder doch reduziert, hell und clean? Moody oder leuchtend? Zeitlos oder modern? Sucht Euch unter unterschiedlichen Atmosphären genau den Look aus, der am besten zu Euch passt!

**Comment by Ironleaves** [comment]
Wenn ich nicht gerade als Fotografin fleißig Pärchenfotos schieße, bin ich freiberufliche Grafikdesignerin für Ironleaves Design[---LINK WEBSITE IRONLEAVES DESIGN---]. Egal was ihr braucht – ich helfe euch, ein individuelles Design zu entwickeln, was zu eurer Hochzeit passt. Dabei können wir eure Farben, Blumen und Deko einbeziehen. Wir finden gemeinsam euren Stil und ich gestalte die Save-the-Date-Karten, Einladungen, Menükarten und Sitzpläne nach Euren Vorstellungen. Garantiert einzigartig und mit viel Liebe gemacht!

In der ganzen Zeit kann ich euch bei euren Planungen unterstützen. Das gibt euch die Sicherheit, dass ihr nichts vergesst und ihr könnt eure Papeterie entspannt mir überlassen. Und falls ich Euch sogar als Hochzeitsfotografin begleiten darf, können wir uns in Ruhe im Vorfeld beschnuppern und vielleicht schon schöne Fotos von einem Kennenlern-Shooting in die Gestaltung einbeziehen. ;)

**Comment by Ironleaves** [comment]
ironleaves-photography-stories-julia-martin-slider-blick-in-die-augen.jpg
ironleaves-photography-stories-julia-martin-slider-brautpaar-laufend.jpg
ironleaves-photography-stories-julia-martin-slider-bruecke-urban.jpg
ironleaves-photography-stories-julia-martin-slider-sonnenuntergang-shooting.jpg
ironleaves-photography-stories-julia-martin-slider-naehe-natuerlichkeit.jpg
ironleaves-photography-stories-julia-martin-slider-stadtpark.jpg
ironleaves-photography-stories-julia-martin-slider-tanzend-in-der-stadt.jpg
ironleaves-photography-stories-samira-kerem-slider-kuss-wiese-sonnenuntergang.jpg
ironleaves-photography-stories-samira-kerem-slider-lens-flare.jpg
ironleaves-photography-stories-samira-kerem-slider-lensflare.jpg
ironleaves-photography-stories-samira-kerem-slider-tanz-ungestellt.jpg
ironleaves-photography-stories-samira-kerem-slider-wald-panorama.jpg
ironleaves-photography-stories-samira-kerem-slider-wald-verliebt.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-reportage-seifenblasen-einmarsch.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-reportage-shooting-pfuetze-spiegelung-abends.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-kuss-park-hofgarten-bayreuth.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-probe-tanz-parkplatz.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-schnappschuss.jpg
ironleaves-photography-stories-sandra-jonas-hochzeit-slider-shooting-verliebt-vertraulichkeit.jpg
ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-spontaner-kuss.jpg
ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-tanzend-ungestellt.jpg
ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-schlossgarten-eckersdorf.jpg
ironleaves-photography-stories-sandra-jonas-standesamt-slider-reportage-kuss-verheiratet.jpg
ironleaves-photography-stories-valerie-max-ehrlich-ungestellt.jpg
ironleaves-photography-stories-valerie-max-eskimo.jpg
ironleaves-photography-stories-valerie-max-hochzeitskleid.jpg
ironleaves-photography-stories-valerie-max-laecheln.jpg
ironleaves-photography-stories-valerie-max-wald-rueckenansicht.jpg

**Comment by Ironleaves** [comment]
https://pin.it/5AYXAc3
https://www.facebook.com/Ironleaves-Photography-110234704840320
